[core]
dist = "dist"

[build]
target = "index.html"
dist = "dist"
public_url = "/"

[watch]
ignore = ["dist"]

[serve]
addresses = ["127.0.0.1"]
port = 3000
open = false

[[proxy]]
backend = "http://127.0.0.1:8000/api/"

[clean]
cargo = true
